# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eduorg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='Python', max_length=20, verbose_name='课程名称')),
                ('course_context', models.TextField(blank=True, null=True, verbose_name='课程描述')),
                ('course_level', models.CharField(choices=[('低级', '低级'), ('中级', '中级'), ('高级', '高级')], default='低级', max_length=4)),
                ('course_students', models.IntegerField(default=0, verbose_name='上课人数')),
                ('course_length', models.IntegerField(default=0, verbose_name='课程时长')),
                ('course_chapter', models.IntegerField(default=0, verbose_name='课程章节')),
                ('course_field', models.CharField(blank=True, default='Python', max_length=200, null=True, verbose_name='课程类别')),
                ('course_follower', models.IntegerField(default=0, verbose_name='收藏')),
                ('course_detail', models.TextField(blank=0, null=0, verbose_name='课程详情')),
                ('course_cover', models.ImageField(default='PubCourse/default.jpg', upload_to='PubCourse/%Y/%M', verbose_name='课程封面')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduorg.Orgnization', verbose_name='课程机构')),
                ('tch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduorg.OrgTeacher', verbose_name='上课老师')),
            ],
            options={
                'verbose_name': '公开课',
                'verbose_name_plural': '公开课',
            },
        ),
    ]
