# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orgnization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='慕课网', max_length=20, verbose_name='机构名称')),
                ('org_area', models.CharField(blank=True, max_length=200, null=True, verbose_name='所在地区')),
                ('org_type', models.CharField(choices=[('培训机构', '培训机构'), ('高校', '高校'), ('个人', '个人')], default='个人', max_length=8)),
                ('org_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='机构地址')),
                ('org_hotcourse', models.CharField(blank=True, max_length=100, null=True, verbose_name='经典课程')),
                ('org_detail', models.TextField(blank=True, null=True, verbose_name='机构简介')),
                ('org_image', models.ImageField(default='eduservice/default_org.png', upload_to='eduservice/%Y/%M', verbose_name='机构封面')),
            ],
            options={
                'verbose_name': '机构信息',
                'verbose_name_plural': '机构信息',
            },
        ),
        migrations.CreateModel(
            name='OrgTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tch_name', models.CharField(default='匿名', max_length=20, verbose_name='教师姓名')),
                ('tch_image', models.ImageField(default='eduservice/default_tch.png', upload_to='eduservice/%Y/%M', verbose_name='教师照片')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduorg.Orgnization')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
    ]
