# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 14:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, verbose_name='课程名称')),
                ('course_context', models.CharField(blank=True, max_length=255, null=True, verbose_name='课程描述')),
                ('course_level', models.CharField(choices=[('E', '低级'), ('M', '中级'), ('H', '高级')], default='E', max_length=2)),
                ('course_students', models.SmallIntegerField(blank=True, null=True, verbose_name='学习人数')),
                ('course_len', models.SmallIntegerField(default=0, verbose_name='时长')),
                ('course_chapters', models.SmallIntegerField(default=0, verbose_name='章节')),
                ('course_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='课程类别')),
                ('course_detail', models.TextField(blank=True, null=True, verbose_name='课程详情')),
                ('course_colleage', models.CharField(blank=True, max_length=20, null=True, verbose_name='授课机构')),
                ('course_teacher', models.CharField(max_length=20, verbose_name='授课教师')),
                ('course_pubdate', models.DateTimeField(default=datetime.datetime(2017, 12, 21, 14, 45, 46, 861211), verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
                'ordering': ('-course_pubdate',),
            },
        ),
    ]
