# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 14:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicCourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiccourses',
            name='course_cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%M', verbose_name='课程封面'),
        ),
        migrations.AlterField(
            model_name='publiccourses',
            name='course_pubdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 14, 49, 7, 98852), verbose_name='发布时间'),
        ),
    ]
