# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 15:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicCourse', '0002_auto_20171221_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiccourses',
            name='course_cover',
            field=models.ImageField(blank=True, null=True, upload_to='PublicCourse/%Y/%M', verbose_name='课程封面'),
        ),
        migrations.AlterField(
            model_name='publiccourses',
            name='course_pubdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 15, 30, 56, 470555), verbose_name='发布时间'),
        ),
    ]
